@startuml CirclePage_SceneGraph.png
node BaseLayout [
    Layout
    "layout/application/default" 
]

node BottomButtonLayout [
    Layout
    "layout/bottom_button/default"
]

node OverLayout [
    Layout
    "layout/application/default"
]
node MoreOption [
    MoreOption
]

node SurfaceLayout [
    Layout
]

node CircleSurface [
    CircleSurface
]
() ContentArea
() BottomButtonArea

BaseLayout --> BottomButtonLayout : "elm.swallow.bg"

BottomButtonLayout --> ContentArea : "default"
BottomButtonLayout --> BottomButtonArea : "elm.swallow.button"
BaseLayout --> OverLayout : "elm.swallow.content"
OverLayout --> MoreOption : "elm.swallow.content"
OverLayout --> SurfaceLayout : "elm.swallow.bg"
MoreOption -[Hidden]l->SurfaceLayout
SurfaceLayout --> CircleSurface
@enduml