@startuml ContextPopup.png

package "Extension.Wearable" {

    class ContextPopup {
        --BindableProperty--
        {static} +SelectedIndexProperty
        {static} +SelectedItemProperty
        --Property--
        +int SelectedIndex
        +ContextPopupItem SelectedItem
        +IList<ContextPopupItem> Items
        --Method--
        +void Show(View anchor)
        +void Show(View anchor, int xOffset, int yOffset)
        +void Show(View anchor, double xOffset, double yOffset)
        +void Dismiss()
    }

    class ContextPopupItem {
        --Property--
        +Label: string
    }

    ContextPopup *-- ContextPopupItem
}

package "Extension.Wearable.Renderer" {
    class ContextPopupImplemetation
    ContextPopupImplemetation .l. ContextPopup
}

package "ElmSharp" {
    class ContextPopup
}

ContextPopupImplemetation *.. ElmSharp.ContextPopup
@enduml

@startuml IndexPage.png

package "Xamarin.Forms" {
    class MultiPage{
        --Property--
        +IList<T> Children
        +T CurrentPage
        +IEnumerable ItemsSource
        +DataTemplate ItemTemplate
        +Object SelectedItem
        --Event--
        +CurrentPageChanged
        +PagesChanged
    }
}

package "Extension.Wearable" {
   class IndexPage {
    }

    IndexPage --|> MultiPage
}


package "Extension.Wearable.Renderer" { 
    class IndexRenderer
    IndexRenderer .l. IndexPage
}

package "ElmSharp" {
    IndexRenderer ... ElmSharp.Index
    IndexRenderer *.. ElmSharp.IndexItem
    IndexRenderer ... ElmSharp.Scroller
}

@enduml

@startuml Check.png

package "Xamarin.Forms" {
    class Switch{
        --BindableProperty--
        {static} +IsToggledProperty
        --Property--
        +bool IsToggled
        --Event--
        +Toggled
    }
}

package "Extension.Wearable" {
   class Check {
        --BindableProperty--
        {static} +DisplayStyleProperty
        --Property--
        +CheckDisplayStyle DisplayStyle
    }

    enum CheckDisplayStyle {
      Default,
      Onoff,
      Small
    }

    Check *-d- CheckDisplayStyle
    Check --|> Switch
}



package "Extension.Wearable.Renderer" { 
    class CheckRenderer
    CheckRenderer .l. Check
}

package "ElmSharp" {
    class Check
}

CheckRenderer *.. ElmSharp.Check
@enduml

@startuml Radio.png

package "Extension.Wearable" {
   class Radio {
        --BindableProperty--
        {static} +ValueProperty
        {static} +IsSelectedProperty
        {static} +GroupNameProperty
        --Property--
        +string Value
        +bool IsSelected
        +string GroupName
        --Event--
        +Selected
    }
}


package "Extension.Wearable.Renderer" { 
    class RadioRenderer
    RadioRenderer .l. Radio
}

package "ElmSharp" {
    class Radio
}

RadioRenderer *.. ElmSharp.Radio
@enduml